#!/usr/bin/env bun
// Delta Chat Web SDK — Integration Test Runner
//
// Uses the multi-account DeltaChatSDK() factory.
//
// Usage:
//   bun run main.ts <server_url> [options]
//
// Tests:
//   --test-invite                         Register + generate invite URI (inviter mode)
//   --test-join <securejoin_uri>          SecureJoin to a peer
//   --test-message <securejoin_uri>       Join + send encrypted message
//   --test-reaction <securejoin_uri>      Join + send message + react to it
//   --test-reply <securejoin_uri>         Join + send message + reply to it (with quote)
//   --test-delete <securejoin_uri>        Join + send message + delete it
//   --test-photo <securejoin_uri>         Join + send profile photo
//   --test-all <securejoin_uri>           Run ALL tests sequentially
//
// Examples:
//   bun run main.ts http://localhost/ --test-invite
//   bun run main.ts http://localhost/ --test-all "https://i.delta.chat/#..."
//   bun run main.ts https://your.server --test-reaction "https://i.delta.chat/#..."

import { DeltaChatSDK } from '../sdk';

// ─── Parse CLI ──────────────────────────────────────────────────────────────────

const args = process.argv.slice(2);
const SERVER_URL = args[0] || '';

if (!SERVER_URL) {
    console.error('❌ Usage: bun run main.ts <server_url> [--test-xxx] [securejoin_uri]');
    console.error('');
    console.error('Tests:');
    console.error('  --test-invite                    Register + wait for incoming SecureJoin');
    console.error('  --test-join <uri>                SecureJoin handshake only');
    console.error('  --test-message <uri>             Join + send encrypted message');
    console.error('  --test-reaction <uri>            Join + send message + reaction');
    console.error('  --test-reply <uri>               Join + send message + reply with quote');
    console.error('  --test-delete <uri>              Join + send message + delete');
    console.error('  --test-photo <uri>               Join + send profile photo');
    console.error('  --test-all <uri>                 Run all tests');
    process.exit(1);
}

// Find the test flag and URI
let testMode = 'all';
let sjURI = '';

for (let i = 1; i < args.length; i++) {
    const a = args[i];
    if (a.startsWith('--test-')) {
        testMode = a.replace('--test-', '');
    } else if (a.startsWith('https://') || a.startsWith('OPENPGP4FPR:')) {
        sjURI = a;
    }
}

// If no --test- flag, default to --test-all if URI given, --test-invite if not
if (!args.some(a => a.startsWith('--test-'))) {
    testMode = sjURI ? 'all' : 'invite';
}

// ─── Disable TLS verification ───────────────────────────────────────────────────
process.env.NODE_TLS_REJECT_UNAUTHORIZED = '0';

function sleep(ms: number) {
    return new Promise(resolve => setTimeout(resolve, ms));
}

// ─── Main ───────────────────────────────────────────────────────────────────────

async function main() {
    console.log('╔══════════════════════════════════════════════╗');
    console.log('║     Delta Chat Web SDK — Integration Test    ║');
    console.log('╚══════════════════════════════════════════════╝');
    console.log(`Server: ${SERVER_URL}`);
    console.log(`Test:   --test-${testMode}`);
    console.log('');

    // Create multi-account SDK manager
    const dc = DeltaChatSDK({ logLevel: 'info' });

    // ── Step 1: Register ──────────────────────────────────────────────────
    console.log('┌─ Register new account');
    const { account: acc, email, password } = await dc.register(SERVER_URL, 'SDK Test User');
    console.log(`│  Email: ${email}`);
    console.log(`│  Password: ${password}`);
    console.log('└─ Done\n');

    // ── Step 2: Keys already generated by register(name) ──────────────────
    console.log('┌─ PGP keypair');
    console.log(`│  Fingerprint: ${acc.getFingerprint()}`);
    console.log('└─ Done\n');

    // ── Step 3: Connect WebSocket ─────────────────────────────────────────
    console.log('┌─ Connect WebSocket');
    await acc.connect();
    console.log('└─ Connected');

    // Demonstrate bidirectional WS protocol: list mailboxes
    try {
        const mailboxes = await acc.wsRequest('list_mailboxes', {});
        console.log(`   WS mailboxes: ${mailboxes.map((m: any) => `${m.name}(${m.messages})`).join(', ')}`);
    } catch (e: any) {
        console.log(`   WS list_mailboxes: ${e.message}`);
    }
    console.log('');

    // Log all incoming messages
    acc.on('DC_EVENT_INCOMING_MSG', ({ msg }: { msg?: any }) => {
        if (!msg) return;
        const tag = msg.isSecureJoin ? '🤝' : msg.isReaction ? '👍' : msg.isDelete ? '🗑️' : msg.encrypted ? '🔒' : '📨';
        console.log(`   ${tag} [UID ${msg.uid}] from=${msg.from} | ${msg.isSecureJoin ? 'SJ:' + msg.secureJoinStep : msg.text.substring(0, 80)}`);
    });

    // ── INVITE MODE ──────────────────────────────────────────────────────
    if (testMode === 'invite') {
        const myURI = acc.generateSecureJoinURI();
        console.log('┌─ INVITER MODE');
        console.log(`│  Account: ${email}`);
        console.log(`│  Fingerprint: ${acc.getFingerprint()}`);
        console.log('│');
        console.log('│  Scan this / paste in Delta Chat:');
        console.log(`│  ${myURI}`);
        console.log('│');
        console.log('└─ Waiting for incoming SecureJoin + messages... Ctrl+C to exit.\n');
        await new Promise(() => {});
        return;
    }

    // All other tests need a SecureJoin URI
    if (!sjURI) {
        console.error('❌ This test requires a SecureJoin URI. Pass it after the flag.');
        console.error('   Example: bun run main.ts http://localhost/ --test-join "https://i.delta.chat/#..."');
        process.exit(1);
    }

    // ── SecureJoin (shared by all tests) ─────────────────────────────────
    console.log('┌─ SecureJoin');
    let peerEmail: string;
    try {
        const result = await acc.secureJoin(sjURI);
        peerEmail = result.peerEmail;
        console.log(`│  Peer: ${peerEmail}`);
        console.log(`│  Verified: ${result.verified}`);
        console.log('└─ Done\n');
    } catch (e: any) {
        console.log(`│  ⚠️  ${e.message}`);
        const parsed = acc.parseSecureJoinURI(sjURI);
        peerEmail = parsed.inviterEmail;
        if (acc.getKnownKeys().has(peerEmail.toLowerCase())) {
            console.log(`│  ✅ Key found for ${peerEmail} — continuing`);
        } else {
            console.log('│  ❌ No key. Cannot proceed.');
            process.exit(1);
        }
        console.log('└─ Partial (unverified)\n');
    }

    // List messages via WS protocol after joining
    try {
        const msgs = await acc.wsRequest('list_messages', { since_uid: 0 });
        console.log(`   WS messages after join: ${msgs.length} message(s) in INBOX`);
    } catch (e: any) {
        console.log(`   WS list_messages: ${e.message}`);
    }

    await sleep(2000);

    // ── JOIN-ONLY ────────────────────────────────────────────────────────
    if (testMode === 'join') {
        console.log('✅ SecureJoin test complete.');
        const myURI = acc.generateSecureJoinURI();
        console.log(`\n┌─ Scan this to message back:\n│  ${myURI}\n└─ Listening... Ctrl+C to exit.\n`);
        await new Promise(() => {});
        return;
    }

    // ── SEND MESSAGE (shared by message, reaction, reply, delete, all) ───
    const tests = testMode === 'all'
        ? ['message', 'reaction', 'reply', 'delete', 'photo']
        : [testMode];

    let msg1: string = '';

    if (tests.some(t => ['message', 'reaction', 'reply', 'delete', 'all'].includes(t))) {
        console.log('┌─ Send encrypted message');
        const msgText = `Hello from Delta Chat Web SDK! 🚀\n\nSent at ${new Date().toLocaleTimeString()}.`;
        const { msgId } = await acc.sendMessage(peerEmail, { text: msgText });
        msg1 = msgId;
        console.log(`│  Message-ID: ${msg1}`);
        console.log('└─ Done\n');
        await sleep(3000);

        // ── REACTION ─────────────────────────────────────────────────────
        if (tests.includes('reaction')) {
            console.log('┌─ Send reaction 👍 to message');
            await acc.sendReaction(peerEmail, { targetMessage: msg1, reaction: '👍' });
            console.log(`│  Reacted to ${msg1}`);
            console.log('└─ Done\n');
            await sleep(3000);
        }

        // ── REPLY ────────────────────────────────────────────────────────
        if (tests.includes('reply')) {
            console.log('┌─ Reply to message (with quote)');
            const originalText = `Hello from Delta Chat Web SDK! 🚀\n\nSent at ${new Date().toLocaleTimeString()}.`;
            const { msgId: reply1 } = await acc.sendReply(peerEmail, {
                parentMessage: msg1,
                text: 'This is a reply! 🧵 Testing quote threading.',
                quotedText: originalText
            });
            console.log(`│  Reply: ${reply1}`);
            console.log(`│  In-Reply-To: ${msg1}`);
            console.log('└─ Done\n');
            await sleep(3000);
        }

        // ── DELETE ───────────────────────────────────────────────────────
        if (tests.includes('delete')) {
            // Send a second message to delete (keep msg1 visible)
            console.log('┌─ Send message #2 (will be deleted)');
            const { msgId: msg2 } = await acc.sendMessage(peerEmail, { text: `This message will be deleted! 🗑️\n\nSent at ${new Date().toLocaleTimeString()}.` });
            console.log(`│  Message-ID: ${msg2}`);
            console.log('└─ Done\n');
            await sleep(3000);

            console.log('┌─ Delete message #2');
            await acc.sendDelete(peerEmail, { targetMessage: msg2 });
            console.log(`│  Deleted: ${msg2}`);
            console.log('└─ Done\n');
            await sleep(2000);
        }
    }

    // ── PROFILE PHOTO ────────────────────────────────────────────────────
    if (tests.includes('photo')) {
        console.log('┌─ Send profile photo');
        const tinyPngB64 = 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8/5+hHgAHggJ/PchI7wAAAABJRU5ErkJggg==';
        acc.setProfilePhotoB64(tinyPngB64, 'image/png');
        await acc.sendProfilePhoto(peerEmail, { data: tinyPngB64, mimeType: 'image/png' });
        console.log(`│  Sent to ${peerEmail}`);
        console.log('└─ Done\n');
    }

    // ── Done ─────────────────────────────────────────────────────────────
    console.log('═══════════════════════════════════════════════');
    console.log(`✅ --test-${testMode} complete!`);

    const myURI = acc.generateSecureJoinURI();
    console.log(`\n┌─ Scan this to message back:\n│  ${myURI}\n└─ Listening... Ctrl+C to exit.\n`);

    await new Promise(() => {});
}

main().catch((e) => {
    console.error('\n❌ Fatal error:', e.message);
    process.exit(1);
});
